module.exports = {
  EMAIL_API_KEY:'',
  EMAIL_DOMAIN:'',
  MAP_BOX_USER: '',
  MAP_BOX_API_KEY:'',
  MAP_BOX_MAP_ID: '',
  GOOGLE_API_KEY: '',
  GOOGLE_CALENDAR_ID: '',  
  FACEBOOK_APP_ID: '',
  FACEBOOK_SECRET: '',
  FACEBOOK_NAMESPACE: '',
  FACEBOOK_CALLBACK_URL: '',
  FACEBOOK_GROUP: '',  
};
